{% set name = "transformers" %}
{% set version = "4.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b14f8c06534246148736fe3d3f0c58c26589c3ce33209ef3208b15bbb5039e8b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - requests
    - tqdm >=4.27
    - tokenizers >=0.10.1,<0.11
    - huggingface_hub
    - dataclasses
    - packaging
    - filelock
    - regex !=2019.12.17
    - sacremoses
    - pyyaml
    - pytorch

test:
  imports:
    - transformers
    - transformers.benchmark
    - transformers.commands
    - transformers.data
    - transformers.data.datasets
    - transformers.data.metrics
    - transformers.data.processors
    - transformers.models
    - transformers.pipelines
    - transformers.sagemaker
    - transformers.utils

  commands:
    - transformers-cli --help

about:
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  doc_url: https://huggingface.co/transformers/

extra:
  recipe-maintainers:
    - mxr-conda
    - roccqqck
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
    - hadim
