{% set name = "transformers" %}
{% set version = "4.57.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55e44126ece9dc0a291521b7e5492b572e6ef2766338a610b9ab5afbb70689d3

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - filelock
    - huggingface_hub >=0.34.0,<1.0
    - numpy >=1.17
    - regex !=2019.12.17
    - requests
    - safetensors >=0.4.1
    - packaging >=20.0
    - pyyaml >=5.1
    - tqdm >=4.27
    - tokenizers >=0.22,<=0.23

test:
  requires:
    - python {{ python_min }}
  imports:
    - transformers
    - transformers.commands
    - transformers.data
    - transformers.kernels
    - transformers.models
    - transformers.pipelines
    - transformers.utils

  commands:
    - transformers env
    - transformers --help

about:
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  doc_url: https://huggingface.co/transformers/

extra:
  recipe-maintainers:
    - mxr-conda
    - roccqqck
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
    - zbowling
