{% set name = "transformers" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f5634efed6cf76ad068cc5834c7adbc32db78bbd6211fb70df2325a9c37dec8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - datasets !=2.5.0  # Required for transformers-cli.
    - filelock
    - huggingface_hub >=1.3.0,<2.0
    - numpy >=1.17
    - regex !=2019.12.17
    - requests
    - safetensors >=0.4.1
    - packaging >=20.0
    - pyyaml >=5.1
    - tqdm >=4.27
    - tokenizers >=0.22,<=0.23

test:
  requires:
    - python {{ python_min }}
  imports:
    - transformers
    - transformers.cli
    - transformers.data
    - transformers.distributed
    - transformers.generation
    - transformers.integrations
    - transformers.loss
    - transformers.models
    - transformers.pipelines
    - transformers.quantizers
    - transformers.utils

  # Disabling until https://github.com/huggingface/transformers/issues/36244 is resolved.
  # commands:
  #   - transformers-cli --help

about:
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  doc_url: https://huggingface.co/transformers/

extra:
  recipe-maintainers:
    - mxr-conda
    - roccqqck
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
    - zbowling
