{% set name = "transformers" %}
{% set version = "4.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 478e1709738237aa1b7bae1fd0ba7bd9d44352fe45972df7ed060077257e84f9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - dataclasses
    - requests
    - datasets !=2.5.0  # Required for transformers-cli.
    - filelock
    - huggingface-hub >=0.14.1,<1.0
    - importlib_metadata
    - numpy >=1.17
    - regex !=2019.12.17
    - sacremoses
    - safetensors
    - packaging >=20.0
    - pyyaml
    - pytorch >=1.9,!=1.12.0
    - tokenizers >=0.11.1,!=0.11.3,<0.14
    - tqdm >=4.27

test:
  imports:
    - transformers
    - transformers.benchmark
    - transformers.commands
    - transformers.data
    - transformers.data.datasets
    - transformers.data.metrics
    - transformers.data.processors
    - transformers.models
    - transformers.pipelines
    - transformers.sagemaker
    - transformers.utils

  commands:
    - transformers-cli --help

about:
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  doc_url: https://huggingface.co/transformers/

extra:
  recipe-maintainers:
    - mxr-conda
    - roccqqck
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
