{% set name = "transformers" %}
{% set version = "4.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc2ae61bfbfaa45337fd9017326669fc60e4f55125f589d50da47819e3d6f504

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - dataclasses
    - requests
    - datasets !=2.5.0  # Required for transformers-cli.
    - filelock
    - huggingface_hub
    - importlib_metadata
    - numpy >=1.17
    - regex !=2019.12.17
    - sacremoses
    - safetensors
    - packaging >=20.0
    - pyyaml
    - tqdm >=4.27
    - tokenizers >=0.14

test:
  imports:
    - transformers
    - transformers.benchmark
    - transformers.commands
    - transformers.data
    - transformers.kernels
    - transformers.models
    - transformers.pipelines
    - transformers.tools
    - transformers.utils

  commands:
    - transformers-cli --help

about:
  home: https://github.com/huggingface/transformers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  doc_url: https://huggingface.co/transformers/

extra:
  recipe-maintainers:
    - mxr-conda
    - roccqqck
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
