schema_version: 1

context:
  name: transformers
  version: 5.13.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 1e2452d6778a7482158df5d5dacf6bf775d5b2fdcfce33caaf7f6b0e5f3e3397

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - transformers=transformers.cli.transformers:main

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - huggingface_hub >=1.5.0,<2.0
    - numpy >=1.17
    - packaging >=20.0
    - pyyaml >=5.1
    - regex >=2025.10.22
    - tokenizers >=0.22.0,<=0.23.0
    - typer
    - safetensors >=0.8.0
    - tqdm >=4.60
tests:
  - python:
      imports:
        - transformers
        - transformers.cli
        - transformers.data
        - transformers.distributed
        - transformers.generation
        - transformers.integrations
        - transformers.loss
        - transformers.models
        - transformers.pipelines
        - transformers.quantizers
        - transformers.utils
      python_version:
        - ${{ python_min }}.*
        - '*'
  # Still broken, but with a fix at https://github.com/huggingface/transformers/pull/45999 (closed as stale)
  #- requirements:
  #    run:
  #      - python ${{ python_min }}.*
  #  script:
  #    - transformers --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  homepage: https://github.com/huggingface/transformers
  documentation: https://huggingface.co/transformers/

extra:
  recipe-maintainers:
    - mxr-conda
    - roccqqck
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
    - zbowling
    - xhochy
